version: "3.8"

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend-app:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: backend-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/kpi_db
    depends_on:
      - mongodb

  frontend-app:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: frontend-app
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend-app

volumes:
  mongo_data:

