version: "3.8"

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /root/project/kpi-management-system/mongo_data:/data/db

  backend-app:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: backend-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend-app:
    build:
      context: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend-app
