@BASE_URL=http://localhost:3000/api/v1

### login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "Aa112244"
}

### profile
GET {{BASE_URL}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDNiYzNkZjFiODI2OGU0ZWI4MzcwZCIsImlhdCI6MTc1ODgwNzY4MywiZXhwIjoxNzU4ODE0ODgzfQ.GiPUIKQK-NCigsPCVeCj5ciPfV539fyQsaOXWgmUoVY
