@BASE_URL=http://localhost:3000/api/v1

###
GET {{BASE_URL}}/dashboard/analytics/achieved
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODk1Nzg2NCwiZXhwIjoxNzU4OTkzODY0fQ.i3k2xjCaVCSrYgZ3PIaK6KOAl2j2L75K42QjnQZGEuk

###
GET {{BASE_URL}}/dashboard/analytics/trends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODk1Nzg2NCwiZXhwIjoxNzU4OTkzODY0fQ.i3k2xjCaVCSrYgZ3PIaK6KOAl2j2L75K42QjnQZGEuk

###
GET {{BASE_URL}}/dashboard/analytics/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODk1Nzg2NCwiZXhwIjoxNzU4OTkzODY0fQ.i3k2xjCaVCSrYgZ3PIaK6KOAl2j2L75K42QjnQZGEuk


###
GET {{BASE_URL}}/dashboard/analytics/status?userId=68d6cec9ff944c1589e50f7d&status=Off Track
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODk1Nzg2NCwiZXhwIjoxNzU4OTkzODY0fQ.i3k2xjCaVCSrYgZ3PIaK6KOAl2j2L75K42QjnQZGEuk
