@BASE_URL=http://localhost:3000/api/v1

###
GET {{BASE_URL}}/dashboard/analytics/achieved?userId=68d6cec9ff944c1589e50f7d&status=On Track
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODkwODE1NywiZXhwIjoxNzU4OTQ0MTU3fQ.3qs2DTSZmOoEUIvxpJ0faG9Jf1NG3GBhOtd9Rcefjrk

###
GET {{BASE_URL}}/dashboard/analytics/trends?userId=68d6cec9ff944c1589e50f7d&status=On Track
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODkwODE1NywiZXhwIjoxNzU4OTQ0MTU3fQ.3qs2DTSZmOoEUIvxpJ0faG9Jf1NG3GBhOtd9Rcefjrk

###
GET {{BASE_URL}}/dashboard/analytics/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODkwODE1NywiZXhwIjoxNzU4OTQ0MTU3fQ.3qs2DTSZmOoEUIvxpJ0faG9Jf1NG3GBhOtd9Rcefjrk


###
GET {{BASE_URL}}/dashboard/analytics/status?userId=68d6cec9ff944c1589e50f7d&status=On Track
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDZhMThiY2E1NWQxYjllMzhjMGYyMSIsImlhdCI6MTc1ODkwODE1NywiZXhwIjoxNzU4OTQ0MTU3fQ.3qs2DTSZmOoEUIvxpJ0faG9Jf1NG3GBhOtd9Rcefjrk
