@BASE_URL=http://localhost:3000/api/v1

# admin only
### create user 
POST {{BASE_URL}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDI5NzA3NzdmYmVjZjhlZjY1NDg2NCIsImlhdCI6MTc1ODcwNjY1NywiZXhwIjoxNzU4NzEzODU3fQ.whz9f9UfoJEsVZB6Hap_LcZqfyVNZOylqCn44GB27yM
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDM1ZWRhNzdlMWQ1MTcyMTczZjc3YSIsImlhdCI6MTc1ODY4Mjg2MywiZXhwIjoxNzU4NjkwMDYzfQ.9v7SqCWks6-AomR1O1O-zBk4PW8csOh5Qa5QzNPtA3s

{
    "username": "user444",
    "password": "Aa112233",
    "email": "user444@gmail.com",
    "role_id": "68d292130cd7093b3b5259a4"
}


### list user
GET {{BASE_URL}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDI5NzA3NzdmYmVjZjhlZjY1NDg2NCIsImlhdCI6MTc1ODcwNjY1NywiZXhwIjoxNzU4NzEzODU3fQ.whz9f9UfoJEsVZB6Hap_LcZqfyVNZOylqCn44GB27yM
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDM1ZWRhNzdlMWQ1MTcyMTczZjc3YSIsImlhdCI6MTc1ODY4Mjg2MywiZXhwIjoxNzU4NjkwMDYzfQ.9v7SqCWks6-AomR1O1O-zBk4PW8csOh5Qa5QzNPtA3s

### get user detail 
GET {{BASE_URL}}/users/68d2970777fbecf8ef654864
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDI5NzA3NzdmYmVjZjhlZjY1NDg2NCIsImlhdCI6MTc1ODY4MjAzNSwiZXhwIjoxNzU4Njg5MjM1fQ.ATUeVdzyKNiBa41j1hWlkflsWswY6_IFNzmX2b1JMKw
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDM1ZWRhNzdlMWQ1MTcyMTczZjc3YSIsImlhdCI6MTc1ODY4Mjg2MywiZXhwIjoxNzU4NjkwMDYzfQ.9v7SqCWks6-AomR1O1O-zBk4PW8csOh5Qa5QzNPtA3s


###  update 
PUT   {{BASE_URL}}/users/68d68cc0c5b17606b6dfbb17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDI5NzA3NzdmYmVjZjhlZjY1NDg2NCIsImlhdCI6MTc1ODg4OTc2MywiZXhwIjoxNzU4ODk2OTYzfQ.MpT3a9aTBVgqI669e_hhbpLwvxEhmAFzJBCq8PXIBEM

{
    "password": "Aa112233",
    "role_id": "68d292130cd7093b3b52599e"
}

###  delete user 
DELETE  {{BASE_URL}}/users/68d296da77fbecf8ef654856
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDI5NzA3NzdmYmVjZjhlZjY1NDg2NCIsImlhdCI6MTc1ODY4MjAzNSwiZXhwIjoxNzU4Njg5MjM1fQ.ATUeVdzyKNiBa41j1hWlkflsWswY6_IFNzmX2b1JMKw
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDM1ZWRhNzdlMWQ1MTcyMTczZjc3YSIsImlhdCI6MTc1ODY4Mjg2MywiZXhwIjoxNzU4NjkwMDYzfQ.9v7SqCWks6-AomR1O1O-zBk4PW8csOh5Qa5QzNPtA3s
