name: Deploy App

on:
  push:
    branches: [ "main" ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}


      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Upload backend .env
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cat > /root/project/kpi-management-system/backend/.env << EOL
            ${{ secrets.ENV_BACKEND }}
            EOL
          EOF

      - name: Upload frontend .env
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cat > /root/project/kpi-management-system/frontend/.env.production << EOL
            ${{ secrets.ENV_FRONTEND }}
            EOL
          EOF

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cd /root/project/kpi-management-system
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF
